organization_id      = "975241469397"
project_id           = "dt-timeseries"
billing_account      = "01CC27-3EC446-644ADC"
cloud_run_sa         = "sa-transcription-pubsub-invoker"
location             = "europe-west1"
terraform_sa         = "sa-transcription-gh-tf-runner@dt-timeseries.iam.gserviceaccount.com"
artifact_registry    = "audio-transcription-service"