organization_id      = "975241469397"
project_id           = "prj-dvt-asr-apis"
billing_account      = "01CC27-3EC446-644ADC"
cloud_run_sa         = "sa-asr-pubsub-invoker"
location             = "europe-west1"
terraform_sa         = "sa-asr-service-gh-tf-runner@prj-dvt-asr-apis.iam.gserviceaccount.com"
artifact_registry    = "audio-asr-api-services"
storage_bucket       = "bkt-asr-audio-files"